language: csharp
matrix:
  include:
    - mono: latest
    
branches:
  only:
    - master
    - develop
    
solution: Fluffy.sln
install:
  - nuget restore Fluffy.sln
script:
   - msbuild Fluffy.sln /m /t:Rebuild /p:Configuration=ReleaseBuild 
    #- xbuild Fluffy.sln /m /t:Rebuild /p:Configuration=Release /p:TargetFrameworkVersion='v4.0' /p:DefineConstants="NET40"
    # - msbuild Fluffy.sln /m /t:Rebuild /p:Configuration=Release /p:TargetFrameworkVersion='v4.6' /p:DefineConstants="NET46"
    # - msbuild Fluffy.sln /m /t:Rebuild /p:Configuration=Release /p:TargetFrameworkVersion='v4.7' /p:DefineConstants="NET47"
#OLD:   - xbuild Fluffy.sln /p:TargetFrameworkVersion="v4.7";DefineConstants="TRACE;DEBUG;NET47"
